### ISSUE TITLE
partner user told that event is not public when it is public

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1025]
Here's a screenshot from https://github.com/USGS-WiM/whispersservices_django/issues/373:
![image](https://user-images.githubusercontent.com/49287076/81869829-5383a680-953a-11ea-9996-041d9c460063.png)

Maybe it's been this way and I've just missed it in the past?? I'm weirded out by the fact that the abilenetest user (who isn't event owner, isn't in the event owner's org, and isn't a collaborator) is being told that this event is not visible to the public when in fact it is visible to the public but it's just that privileged details are not visible to abilenetest.

**Comment by BlakeDraper** [comment]
@JChipault working through this now, but can you tell me if this seems right to you - that entire privileged event data section should not be visible to this user since they have no permissions on it? the page should look just like it would to a public or non-authenticated user where only the top half is visible with the public data.

The issue here is I am determining visibility of that section based on role, instead of on permissions. As Aaron said, lack of that field due to permissions is causing this (wrong) indicator that the event is not public. I think we should simply be hiding that section to users who have no permissions to it anyway.

**Comment by BlakeDraper** [comment]
After discussion, Aaron and I arrived at a two-part solution for this.

1) Aaron will add a boolean field called `is_privileged_user` to the eventdetails response which will positively identify whether the requesting user has any permissions to view privileged data (either because they are the event owner, in the event owner's org, or are a collaborator). This will be used to determine visibility of the Privileged Data section in a more reliable way than user Role alone (which is the current arrangement).

2) The Request to Collaborate button will move out of the Privileged Event Data section in order to make it useful to authenticated Partner Users (and above) who wish to collaborate on the event but who don't currently have any permissions to view its privileged fields.

**Comment by aaronstephenson** [comment]
For 1 above, I have implemented the field in 82ac344b

**Comment by JChipault** [comment]
amazing. One point of clarification: the Request to Collaborate button should be visible to Affiliates too (just not public or non-logged in users)

**Comment by BlakeDraper** [comment]
@JChipault @nbaertlein Just piggy-backing on this discussion a bit: for the 'NWHC-only' fields, we have that written as only available to the SuperAdmin and Admin roles. That is, a NWHC org user who is not one of those roles (even a PartnerManager) does not have that access. Is this correct?

**Comment by JChipault** [comment]
@nbaertlein should weigh in but I've been thinking the "NWHC-only" fields would be available to anyone in the NWHC org, regardless of role. But if that's more complicated for development, I think we can easily work with those fields being restricted to WHISPers Admin or SuperAdmin

**Comment by aaronstephenson** [comment]
It's not too complicated. I'm happy to make the change if necessary, I want to ensure we get this right.

**Comment by BlakeDraper** [comment]
The client app aspect of this is done as of v2.15.2.

**Comment by JChipault** [comment]
Looks good! So much better. Only lingering thing I see is that when I logged in as an affiliate and looked at an event that I wasn't a collaborator on, I still see the warning on the bottom of the map. When I'm a public user, I don't see this warning.
![image](https://user-images.githubusercontent.com/49287076/82065449-b9d00c80-9693-11ea-8bad-95682b696f2d.png)

**Comment by BlakeDraper** [comment]
Tweaked that in code. Waiting to do another release, to see if anything else minor arises.

**Comment by BlakeDraper** [comment]
done with v2.15.3
