### ISSUE TITLE
add collaboration circle on event details page

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1058]
On the event details page, when I try to add a circle of collaborators, I get this message.

![image](https://user-images.githubusercontent.com/49287076/94273773-75d6f900-ff0a-11ea-9d4c-3c9cccef4b80.png)

As shown in this screenshot, the names show on the webpage even though I get this toast message. But if I leave the event and come back to it, then the names are gone. 

When I tried adding myself as a collaborator on a test site event, I did get an email telling me that I had been added as a collaborator, but when I looked at the event on the WHISPers test site, I wasn't listed as a collaborator there. So the notification emails are getting triggered but the data aren't saving to the event.

I seem to be able to add circles on the create event interface just fine so perhaps the code there could inform the code on the event details page.

I CAN add individuals as collaborators; seems to just be an issue with circles on the event details page.

Same behavior happens for read only and read/write.

**To Reproduce**
Go to an event details page, click "view collaborators", click "add circle" under either read only or read/write, select a circle, click done.
Leave event and come back to event

**Desktop (please complete the following information):**
Happens in Firefox and Chrome

**Comment by BlakeDraper** [comment]
Fixed and released in v2.15.5

**Comment by JChipault** [comment]
I just tried this on the test site and hit an error message again. When I added the "Jenny Only" circle to 170962, I got this: 
![image](https://user-images.githubusercontent.com/49287076/102094897-78017300-3de8-11eb-94eb-78e35edc46c6.png).  Is this because I'm also the event owner? (see github 1102). Also tried with a "circle" that only had Ali and got JSON error message.

**Comment by JChipault** [comment]
Hmmm... getting JSON error on test site when trying to add individuals, too. Tried to add abilenetest user as an individual collborator on 170960.  However, it appears adding an individual is working on the live site because I see that 200990 that was created today has a collaborator on it. I did not do any more fussing on the live site.

**Comment by BlakeDraper** [comment]
@aaronstephenson This is what I get when I attempt to update the collaborators list:

![image](https://user-images.githubusercontent.com/6978380/102643899-9687a700-4125-11eb-98e3-cd0b50fba7f8.png)

JSON for easier copy:
```
{
  "id": 170962,
  "event_type": 1,
  "new_read_collaborators": [
    6
  ],
  "new_write_collaborators": [
    4
  ]
}
```

When I first tried this, I had only the `new_read_collaborators` array populated and the other empty, so I thought that was the issue. But as you see, even with both populated, it errors out. We recently fixed this back in early October - back then the client was sending a malformed request. Did something revert on the backend, or maybe it somehow did on the front end? Let me know if that JSON request is malformed.

**Comment by aaronstephenson** [comment]
OK, so the earlier "fix" for this worked for creating collaborators when creating new events, but clearly I didn't fully test it when trying to update collaborators for existing events. Using Blake's example, I found that I was using the wrong kind of reference in the update code block. I was trying to look up a User object from a variable, which in the create code block contains an integer value, but in the update code block already contains a User object (one of the "magic" things that Django does that I sometimes forget about). So the code as written was returning an error when you try to update the collaborators list on an existing event, because the code was trying to look up an object using an object (instead of an integer), causing the TypeError seen in Blake's screen capture.

I have now fixed this and will push it the fix the servers shortly.

**Comment by aaronstephenson** [comment]
Fix pushed to test server.

**Comment by aaronstephenson** [comment]
Fix pushed to prod server.

**Comment by BlakeDraper** [comment]
Fixed on backend repo.
