### ISSUE TITLE
Search selection type ahead + mouse click

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#1120]
@machristie 
In the search panes, the mouse selection does not work after type ahead entry (for species, diagnosis type, event diagnosis, state, or county).  Mouse click of selection will not populate criteria and will clear typed text.

![image](https://user-images.githubusercontent.com/38669574/105403516-76e51200-5bee-11eb-89ba-0e7325c60347.png)

**Comment by nbaertlein** [comment]
Type ahead + mouse click will work for first 1 or 2 entries on the list (i.e. diagnosis type: Bacteria, State: Alaska, Alabama), but will not work for any other entries.

**Comment by JChipault** [comment]
This seems to work just fine in Firefox but does not work in Chrome (as described above)

**Comment by machristie** [comment]
The issue is that in Chrome, at least, the input field is blurred before option selection happens, which resets the input field. Found this related issue in angular material: https://github.com/angular/components/issues/19536

Fix was pretty simple, just need to check in the onblur handler if an option has been selected, otherwise the input control can be reset.

**Comment by BlakeDraper** [comment]
Published in v2.16.4.
