### ISSUE TITLE
Document UI design guidelines

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1162]
Document guidelines on how to use UI elements in the WHISPers app. Document code snippets that can be used and best practices.

**Comment by machristie** [comment]
@BlakeDraper The WHISPers team and I have developed some UI design guidelines as part of the SGCI engagement and I want to document those. I'm trying to figure out the best place to put this documentation. I haven't used compodoc before but additional documentation, beyond the automatically generated docs it creates from the source code, can be added to it: https://compodoc.app/guides/tips-and-tricks.html#additional-documentation. So I was thinking about using that approach with the goal of keeping the docs all in one place. Does that sound good or do you have any suggestions?

**Comment by BlakeDraper** [comment]
@machristie that makes sense to me, if the documentation's audience is WHISPer users, which it sounds like it is. I was pretty hands off with the compdoc stuff and it is not really fine-tuned, but you could still use it. Otherwise I'd maybe just make it a simple HTML webpage that NWHC can host on their website.

**Comment by machristie** [comment]
@BlakeDraper the audience is for developers. I figured it would be better to keep it with the repo so it is handy to developers. Is the compodoc documentation used much? If not, maybe that's not the best place for it. Other options would be:
* a Markdown file in the repo, maybe UI_GUIDELINES.md in the root folder
* a Github Wiki page, which might be ideal because NWHC folks could also contribute to it

Thinking about it more, I think the Wiki page might be the best option.

**Comment by BlakeDraper** [comment]
I am partial to markdown documents. I already write all my notes in Markdown and would write everything in Markdown if I could. So I support that. That would work either as an MD file or in the Wiki. I am inclined toward the MD file in the repo because it is then portable with the repo and easier to find, IMO. I often forget github wikis exist. So let's do that for now. If I later find they are wanting to edit it and MD file format it causing friction, I'll move it to the Wiki. Thanks!

**Comment by machristie** [comment]
Sounds good, thanks @BlakeDraper

**Comment by BlakeDraper** [comment]
Published in v2.16.6.
