### ISSUE TITLE
business rules for population not working as expected on event details page

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1250]
**Describe the bug**
On create event, the business rule for population is working as expected. If I put in a population of 1 and number dead of 2, I get this warning message:
![image](https://user-images.githubusercontent.com/49287076/146443581-5e6bf11f-c1ae-49dc-ba10-672c83469caf.png)

So that's good!

However, on the event details page, I can edit an event such that the population number is less than the sick or dead and I am allowed to save that change. 
![image](https://user-images.githubusercontent.com/49287076/146443794-73fea3f6-7cae-4c78-a622-3265d316b5dd.png)

And then if I go to clear that population number out altogether (so that it becomes null), I get
![image](https://user-images.githubusercontent.com/49287076/146448537-497dd5d7-c52d-4cce-99c3-fd3a82c2d36f.png)

Or even if I try to make the population number higher than the sick or dead, I get
![image](https://user-images.githubusercontent.com/49287076/146448656-aa116bee-0eb7-4eaa-b243-f34375c45dce.png)

**To Reproduce**
1. Go to any event that has no population number listed for a species
2. Click on the population field
3. Enter a number less than the sick or dead tally
4. Save
5. Note that you're allowed to save
6. Go back to the population field
7. Try to null it out
8. Get error message
9. Go back to the population field
10. Try to make it greater than the sick or dead tally
11. Get error message

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BlakeDraper** [comment]
@JChipault Do I understand correctly that we should allow Population to be empty / null, when there is a greater than 0 sick/dead count sum, but not allow an actual number for Population less than the sum of the dead and sick count?

#### Notes for WIM
Bugs: 
1. POST to /api/locationspecies/{id}/ allows population_count less than dead_count, dead_count_estimated, sick_count, sick_count_estimated

expected behavior: should be prevented per business rules

2. POST to /api/locationspecies/{id}/ throws error if  population_count is null when there is any sum greater than 0 among  dead_count, dead_count_estimated, sick_count, sick_count_estimated

expected behavior: should be allowed per business rules (_tentative - awaitng NWHC confirmation_)

**Comment by JChipault** [comment]
correct

**Comment by BlakeDraper** [comment]
Being handled on the backend: https://github.com/USGS-WiM/whispersservices/issues/532
