### ISSUE TITLE
home page map not accounting for legend when displaying dots

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1299]
**Describe the bug**
There are event dots on the home page map that are under the legend. I think when we decided to default the legend to open, that we worked on re-centering the dots such that the legend was taken in to account. This might have been something done when Marcus from SGCI was helping us.

**To Reproduce**
1. Go to test site
2. Default search loads
3. Notice that some events are under the legend:
![image](https://user-images.githubusercontent.com/49287076/193639580-60753339-397f-4b15-9526-5f9c18795e1a.png)

**Expected behavior**
Event dots are centered after taking in to account the width of the legend. This is working as expected on the live site; screenshot of expected behavior here-
![image](https://user-images.githubusercontent.com/49287076/193640223-15a69caf-7303-44b6-b5ac-bed1380ae39e.png)

Maybe this has been off on the test site for a while and I just hadn't noticed it before now?? It's strange to me that this is off on the test site and fine on the live site.

**Comment by BlakeDraper** [comment]
@JChipault our options are somewhat limited here given our mapping library Leaflet. The offset stuff is a but finicky in combination with the function that dynamically parses the bounds of the displayed dots. In my experimentation, I could only get it to go a little overboard with the offset. If this is a must-fix, due to the time involved in tracking down a better solution,  I am going to have to punt on it for now until we have a more solid plan in place for development this year.

**Comment by JChipault** [comment]
ok, I did some more playing around and we can just ignore this ticket. I can't recreate it on the live site but I also see that it doesn't consistently happen on the test site so, like you said, seems just an oddity of certain groups of dots. Not worth spending any more time on.
