### ISSUE TITLE
Don't let user leave filled-in event submission form

### ISSUE THREAD

**Issue by mitch-wim** [USGS-WiM/whispers#340]
Right now if you fill in the event submission form and navigate away from the page (close tab, click an external link, hit the browser back/forward) you lose everything you filled in.

Add a popup to prevent leaving. 

"Are you sure you want to navigate away from this page? All unsaved changes will be lost"

https://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes

**Comment by BlakeDraper** [comment]
good call

**Comment by lprivette** [comment]
https://stackoverflow.com/questions/35922071/warn-user-of-unsaved-changes-before-leaving-page

Found and followed this because its example solution uses angular 7/typescript.

Alert's display logic is based on the form's `touched` property. If `touched `is false the alert won't fire. I think that's the best option but let me know if there's another way you'd like to check for form entry. Works with browser refresh, close, back, and entering a new url in the address bar.

**Comment by lprivette** [comment]
followed this dood's example to get around the mat dialog issue with return the boolean. Fix was to return it via the `afterClosed` method. https://gist.github.com/Splaktar/dcf2f7e98b4cf3f7b87c1c4ff3e6b2b5

**Comment by BlakeDraper** [comment]
@lprivette tested and seems to be working well
