### ISSUE TITLE
Clear date range in Firefox

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#488]
The clear date range button does not work in Firefox.  Using Firefox v 64.0 released 12/11/18.  Clear selection at the very bottom of search pane works as expected though.
Don't know if it's a WHISPers or Mozilla problem.

![image](https://user-images.githubusercontent.com/38669574/50171270-9e52ad80-02b7-11e9-9124-07333347710a.png)

**Comment by BlakeDraper** [comment]
Fixed

**Comment by JChipault** [comment]
@BlakeDraper seems not fixed in v16 in Firefox

**Comment by JChipault** [comment]
@BlakeDraper still seems not fixed in v17

**Comment by BlakeDraper** [comment]
@JChipault I cannot recreate this button not working. See below for a short GIF of what happens when I try this myself on Firefox. Am I doing the correct thing? 
http://recordit.co/Vk5SBe4Gbk

This was using version 67.0.1 of Firefox, so you may have the same results if you upgrade your version. Unfortunately we cannot necessarily account for every older version of a browser. We can however specify which browser versions are supported by the application in the About dialog. It is actually very strange that this seems to be not working in v64 of Firefox because the code is dead simple and is definitely not the sort of new standard or function that may sometimes be unsupported by old browser versions. In fact, v64 only just came out just this past December.

At any rate, we are not able to pursue this as it appears to possibly be a bug within that specific version of Firefox - again our code is dead simple for that clearing action and there is no real room for refactor or improvement.

**Comment by JChipault** [comment]
ok, thanks for looking into this!
