### ISSUE TITLE
Event diagnosis refresh

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#529]
Event diagnosis drop down options AND selections do not update if species diagnoses are edited or deleted.  This may also affect how it ends up being displayed on event details - no event diagnosis is saved, but should be undetermined or pending.

**Comment by JChipault** [comment]
I tried to demo this today but errantly pulled up the Event Details page to demo... it's the Create Event page wherein the event diagnosis does not update when the species diagnosis is updated. I tried it on the conference room computer (instead of my slow personal computer) and it was still an issue.

**Comment by JChipault** [comment]
In addition to the diagnosis field, it's also the "suspect" status that does not update.

**Comment by BlakeDraper** [comment]
Fixed in code
