### ISSUE TITLE
isTrusted error

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#537]
On 3/15/19 in live beta 10: On first selection of Save Record got a not saved error about is.Trusted.  Then I selected save record again and it saved immediately

On 4/2/19 in test beta 10: Opened event 170707 and tried to enter a service request. The subform seemed to freeze when I hit save (i.e., it didn't do anything) so then I hit cancel and the subform closed. However, the request did commit, seemingly twice (I think?). Tried again and it went smooth. Tried a third time and got this toast message: Error. Service request not submitted. Error message: {"isTrusted":true}. Committed the action 2x after I got the toast message

Might be related to github #534?

**Comment by JChipault** [comment]
Happened again with creation of 200089 and 200090 on 5/29/19.  From user: "When I hit save the first time it gave me error message about "not trusted" so i did not think it saved properly. No email was sent saying 200089 created. I clicked save again and it created 2."

**Comment by JChipault** [comment]
Happened again with service request. Was making request from create event page on the test site (v16) and the form froze and then I got this toast message: Error. Service request not submitted. Error message: {"isTrusted":true}

**Comment by BlakeDraper** [comment]
@JChipault Here is what we are going to do: Aaron is going to do some refactoring of how the Event data is processed on submission. There will be 2 improvements:

1) He will build in a protection for when 3rd-party services break/fail. The FWS Flyways service broke, and that lookup is part of the event location creation, as we have discussed.  We'll be sure that even if that outside service fails, the whole processing of the event data does not.

2) He will build in a new feature that essentially removes all parent data (namely, the event) if something breaks deeper down in the chain. While it may seem that the data you entered was 'dropped', in fact, technically speaking, it was never actually created (in this case most likely due to the failure of the FWS flyways service). But the Event record itself was created, hence the frustrating outcome. We hope to not have failures of the processing, but if they do happen, going forward, the logic will actually delete that event record just created so that if the user clicks "Save Event" again, it does not have the effect of creating duplicate events (since the server has no way of knowing that the new submission is identical to the last).

**Comment by BlakeDraper** [comment]
Done with Aaron's recent changes.
