### ISSUE TITLE
Duplicate events without error message

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#542]
Went through Create Event in the test site v10 and then hit save. The blue bar that indicates that it's saving loaded halfway and then stopped. I never got an error message and I never got the popup that indicates that my event saved. I waited a few minutes and finally just clicked off the create event screen by going back to the home page. I assumed my event did not save, but it saved twice 170713 and170714. I also received two emails for my service request (one for each event).

**Comment by BlakeDraper** [comment]
Need to check on server error for events POST. May have been temporary condition.

**Comment by BlakeDraper** [comment]
This issue raises a few points. 

1) We unfortunately do not have control over network latency for submission. It could take a while for request to complete. This is especially true for a large event submission with lots of data.  It depends on both the user's network and the network at EROS. The success message displays once a  HTTP success response has come back from the server, indicating a completed action.  If the user navigates away from the page before this success message arrives, they will not receive it. Essentially when you Save the event (or save/update/add anything in WHISPers) what is actually happening is a _request_ is sent to the server to make that update. Eventually the server will respond with "yes, I did what you wanted successfully" or "sorry, something went wrong, here is some information on what went wrong".  Either way, the action you requested was set in motion on the server already. The server has no idea that you closed the browser or navigated away from the page in the meantime. It just means the client is no longer listening for the response.

2) Identical events are not a thing we are checking for in any way. So if the submission request succeeds unbeknownst to the user, and the user then makes a new submission request with the exact same event data, there is nothing to prevent that. Due to the potentially huge amount of child data related to an event record, doing a check for an identical event would be a huge computational burden.

**Comment by JChipault** [comment]
On 6/3, one of the epidemiologists using the live site (v13) tried to submit an event, got an error message indicating that the event wasn't submitted, but since he's been down this road before he knew to wait and not hit the save button again. The save button did not grey out so he could have hit it again. But the event eventually submitted and he knew that based on an email arriving at the epidemiology email dropbox. "Save event" button stayed live.     Some thoughts: 1) grey out the save button after a user clicks it (not after the data hit the server), 2) have it try to submit the data multiple times during some period of time (maybe a few seconds) before displaying an error message to the user because it seems like there's a knock on the server door, the server says no thanks, then the user gets an error message, then there's another knock on the server door, and the server lets the data in this time and by then the user is already frantically clicking save again usually. So if there were multiple attempts to commit the data while the user is shown a spinning circle so that they knew data were processing, that might help too.

**Comment by BlakeDraper** [comment]
This is also fixed by the refactor Aaron did this week as discussed.
