### ISSUE TITLE
Update eventgroups response to include event group category and the associated comment

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#543]

**Comment by BlakeDraper** [comment]
It does not seem to be true that it does. I have been trying access it from the superadmin role (user: admin). and these fields are not present.

**Comment by aaronstephenson** [comment]
Which endpoint?

This is what I see at /eventgroups/ when logged in as a superadmin:
![image](https://user-images.githubusercontent.com/8713712/55979806-a4024380-5c58-11e9-876e-cd7b9a356c7f.png)

**Comment by BlakeDraper** [comment]
the fields are not present in the list of all

**Comment by aaronstephenson** [comment]
Yes, that is expected behavior, and has been since the beginning. All list requests always use the public version of the serializer, which have fewer fields. I've asked your opinion on this several times but you've never given me one.

So, do you want these fields to appear in the public EventGroup serializer? Or should we discuss behavior of all list requests?

**Comment by BlakeDraper** [comment]
We need the list to contain those fields for authorized users. This is how the user sees a table of all the Event Groups to review it and take actions.

**Comment by aaronstephenson** [comment]
Special handling of the list action has been removed in 0.126.0 0af3d19 of the whispersservices_django repo.
