### ISSUE TITLE
Event Group - dashboard selection

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#560]
Bug Report #701
Was on Event Groups tab and clicked on G3 and G10, then went to Events tab and it says"Current Event Group Selection: G3 Test. these are Achilles Tang events."... but "these are Achilles Tang events." is the justification for G10, not G3

**Comment by BlakeDraper** [comment]
This issue, along with some other odd behavior,  was caused by the Beta DB having some non-compliant Event Groups that had no events and no justification comment. I am not entirely sure how these were created but may have been some early test items. 

WHISPers does not allow an event group to be created without at least 2 events and a justification comment. I have deleted the offending records, which fixes the behavior you were seeing.
