### ISSUE TITLE
CSRF Token error on Live site

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#585]
Attempting to toggle event complete status to incomplete for event 200078 (also for 200079) and get a CSRF token error:

![image](https://user-images.githubusercontent.com/38669574/58595902-c87da380-8237-11e9-8498-7c3361f25f6b.png)

**Comment by BlakeDraper** [comment]
@nbaertlein you are most likely encountering this error because you are logged in to the WHISPers API interface (image below) while trying to work in the WHISPers client. You need to log out of that before attempting to use the WHISPers client. 

![image](https://user-images.githubusercontent.com/6978380/58637097-5cdb1b00-82b7-11e9-905e-66a9cc65e683.png)

**Comment by nbaertlein** [comment]
That appeared to be the problem.  I was able to make the changes.  Thanks.
