### ISSUE TITLE
cause vs significance of diagnosis popup message

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#591]
Get this message when try to mark an event complete: 
Error. Event not updated. Error message: ["The event may not be marked complete until all of its location species diagnoses have a basis of diagnosis.","The event may not be marked complete until all of its location species diagnoses have a cause."]

Trick is that there's no "cause" field on the front end. Can this say "The event may not be marked complete until all of its location species diagnoses have a significance of diagnosis"

Neil report 627

**Comment by BlakeDraper** [comment]
The correct fix for this is to prevent that error message from displaying. When you see that message, it is because the server has detected a business rule violation and rejected the request.  The best UX is for the WHISPers client to detect that violation _before_ the request is event sent. We need to identify these uncovered cases (which you done by creating this issue) and I need to write a catch and more elegant error notification. 

We do not actually want to change the message coming from the server because it refers to the actual field name.

**Comment by BlakeDraper** [comment]
Added a validation error for lack of Significance and Basis of Diagnosis on selection of Record Status: complete. Also added a validation error for lacking location species numbers ( Known Dead, Estimated Dead, Known Sick, and Estimated Sick) on selection of Record Status: complete. Event Details page. Done in code.

**Comment by JChipault** [comment]
Nice to have a message to indicate what needs to change in order to be able to mark event complete, but I didn't see the message for a while because it took me forever to figure out that I have to scroll down on the subform window to find the red text. Any way to make that red text show without scrolling so that the user is more likely to see it?

**Comment by BlakeDraper** [comment]
I've moved these messages up above the NWHC-only section - look for that change in next release.

**Comment by JChipault** [comment]
Fantastic! Thanks!
