### ISSUE TITLE
can't delete saved searches

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#602]
No way to delete saved searches in dashboard

**Comment by BlakeDraper** [comment]
Lauren is taking a stab at this one. Will most likely be a button/toggle that enacts a Delete 'mode' after which a click on a saved search item prompts the user with a confirmation (using the standardized confirm component) and then deletes the search record on user confirm. User will then need to turn off delete mode to return to click-and-go to execute the search.

**Comment by JChipault** [comment]
What if we limited the delete function to the dashboard? Then could we make it more like the delete function on the contacts tab of the dashboard? It'd be nice if deleting a saved search mirrored the procedure for deleting other things in the dashboard in order to maximize ease of use. And then maybe just some hover over text on the home page to tell users that they can manage their saved searches in their dashboard. Thoughts?

**Comment by BlakeDraper** [comment]
@JChipault The issue with that is the saved searches list is a totally different type of element than the contacts and all the other tabs on the user dashboard page. Those are all tables, which is easy for them to be since the size of the displayed text/data contained within each row is predictable and more consistent across the records. 

The saved searches component displays the searches not as a table, but actually as buttons that contain the entirety of the search text and are highly variable in size because there is no limit on the number of parameters, or the number of values per parameter your search could contain. It does not lend itself well to a table format. 

If we were to orient the searches more towards a table view like the others, we would need to rethink how the search query is displayed and we would almost certainly have to sacrifice readability with something like a truncated view with a click to see details, which adds another click to the process.

**Comment by lprivette** [comment]
Done in code.
