### ISSUE TITLE
live v13 requiring a lab for "Undetermined"

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#605]
Quick heads up that it seems v10 (scratch that... v13) is now requiring a lab when we want to put in Undetermined for species diagnosis. A couple of users have bumped into this. We do still need ability to add undetermined, no suspect checkbox, no lab at the species level.

**Comment by BlakeDraper** [comment]
@JChipault that fix was part of beta.15, so it has not made it to 'live' yet. Should we just begin concurrently releasing new versions to both test and live? Seems to be a lot of confusion about the versions between the two environments. The idea is test should be approved first before being promoted to live, but I have done a poor job of communicating that.

**Comment by JChipault** [comment]
@BlakeDraper Yea, floating v15 to live sounds good. I'm slightly wary of v16 going live yet because of the JSON errors (see other github reports). I like having things on the test site first so that we can check them out there quick. But we should be better about letting you know when it's ok to push from test to live.

**Comment by BlakeDraper** [comment]
@JChipault this is a more general comment on this issue - please only report issues that can be observed or recreated on beta test.  The test version is exactly that- the testing ground for the WHISPers app. The 'live' beta is just the exact same code, or even behind in version as discussed above.  The main difference is the database each one connects to and how we are treating that data. 

From our perspective, the 'live' beta is an arrangement that breaks convention somewhat and it was something we offered only per request so that real data could be be input. Among your testers there seems to be confusion on this and it is creating inefficiencies in this testing and vetting process. 

If a tester runs across an issue on the 'live' beta and they cannot recreate it on the test version, it is not something we wish to investigate because the beta test version is always the latest.

**Comment by JChipault** [comment]
got it. thanks
