### ISSUE TITLE
Event location review incorrectly marking a new Location complete when it still needs a comment

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#674]
![image](https://user-images.githubusercontent.com/23640741/61725682-37f6a780-ad3e-11e9-9df2-99190d0773d1.png)

**Steps to recreate:**
1. Navigate to an existing, incomplete event and add a new event location
2. Populate the following fields: country, state, county, land ownership, species
3. Click step 6 "Review and Submit"

Appears to be related to: https://github.com/USGS-WiM/whispers/issues/555

**Comment by lprivette** [comment]
done in code.

**Comment by JChipault** [comment]
@lprivette These might be more complicated than it's worth right now, but I'll float them here in case it's easy because they feel similar to this fix you just made and I want to catch you while you're familiar with that chunk of code to know how easy these would be or not. 
1) if I enter a state but don't enter a county, the review screen doesn't have a check box nor a red warning message.
2) if you open up a line for a location contact and then don't select a contact, you get no checkbox nor red warning message at the review stage for a location (you do see the blank contact line in red if you flip back through the data entry tabs)
![image](https://user-images.githubusercontent.com/49287076/61900659-a6c13580-aee3-11e9-9df6-1efebfc4c198.png)

**Comment by lprivette** [comment]
Thanks @JChipault Good catches! 
1) Issue is just a typo (just fixed locally)
2) Is a contact person "required"? If it's not, then how about I try to remove the red color suggesting it's mandatory?

**Comment by JChipault** [comment]
1. County is required, I should have made that clear. So system should give me a warning message if I don't have it.
2. Contact person is not required but if the subform gets opened by clicking "Add Contact" then the system is treating it as if it's required because it's been initiated. If the user does not hit "Add Contact" and has no contacts listed, then there's no flag (which is appropriate). If they click "Add Contact" and don't add anyone then, from the user's perspective, there shouldn't a flag ... buuuuut.... I don't know how complicated this is to fix in the code.

**Comment by JChipault** [comment]
#2 has tripped up at least 3 users who have opened up the "add contact" line and then left it blank. They don't get a warning on the review location information screen but they also can't save an event because the "save" button is greyed out. So then it takes a while of flipping back through everything to realize that they have to delete that blank contact line in order to save

**Comment by lprivette** [comment]
Got it. I've opened a separate ticket for tracking #2 (https://github.com/USGS-WiM/whispers/issues/676) and will leave #1 included in this one.

**Comment by JChipault** [comment]
Thanks for fixing the county warning! Realized there's another warning probably missing. If the system is giving you this message at the location review: "An event must have a start date provided for at least one location" then logically something like this should also be on the location review pain: "An event must have a number affected (known sick, estimated sick, known dead, or estimated dead) for at least one species for at least one location." For these two warnings, I think it's fine to have the checkmark and the warning simultaneously at the location review tab, like it's working now for start date.  
![image](https://user-images.githubusercontent.com/49287076/62495935-05689800-b79d-11e9-9a2b-762008b40427.png)

**Comment by JChipault** [comment]
Realizing that my previous comment today might be more related to #675

**Comment by lprivette** [comment]
@JChipault to satisfy the number affected requirement, would all 4 of the fields (known sick, estimated sick, known dead, or estimated dead)  need to be filled out or only one?

**Comment by JChipault** [comment]
Only one. Maybe the wording should change to be more clear: "An event must have at least one number among known sick, estimated sick, known dead, or estimated dead for at least one species for at least one location." Do you think that's better?

**Comment by lprivette** [comment]
Got it. Yep, makes sense to me.

**Comment by lprivette** [comment]
Making the second issue identified into a new issue since this one is already in dev. https://github.com/USGS-WiM/whispers/issues/689
