### ISSUE TITLE
adding "undetermined" species dx without a lab

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#692]
I can add "undetermined" for a species diagnosis, uncheck the "suspect" box, and click save and get it to commit. But then when I go to mark an event as "complete" I'm told (appropriately) that I need to have a basis for diagnosis and a significance of diagnosis. If I select "circumstances such as..." and "cause of death" then I get this error and can't save: 
![image](https://user-images.githubusercontent.com/49287076/63132643-8129c800-bf87-11e9-9a3d-f35d65ead283.png)

**Comment by BlakeDraper** [comment]
@JChipault  Just to be sure I fix this in the correct way, please confirm:  the problem here is an exception to a rule that we have failed to account for. The business rule says any non-suspect diagnosis must have a diagnosing lab. The singular exception to that is the diagnosis "Undetermined" - is that correct?

**Comment by JChipault** [comment]
correct. See #605 and #530. I think this has worked fine before but this bug seems to have crept back in.

**Comment by BlakeDraper** [comment]
Looked into this and it seems like a small change in the underlying library (Angular) actually caused this bug to resurface in the specific case of editing an existing species diagnosis, and only if the suspect toggle or diagnosis was untouched. At any rate, it has been fixed and I will publish a patch update soon.
