### ISSUE TITLE
chunks of map not loading

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#699]
sometimes when you first land on whispers, the home page map doesn't fully load. there are rectangles that are just grey. like this:
![image](https://user-images.githubusercontent.com/49287076/64721996-32425600-d493-11e9-9cc7-a6fe4312e939.png)
after about 20 seconds the upper left filled in and it looked like this: 
![image](https://user-images.githubusercontent.com/49287076/64722043-44bc8f80-d493-11e9-8c1f-6647728bf503.png)
but then it sat like this for over an hour until I hit refresh:
![image](https://user-images.githubusercontent.com/49287076/64722060-4f772480-d493-11e9-866d-4258bb96110f.png)
Same things happens on the event details page map.

**Comment by lprivette** [comment]
This is likely either a network issue (slowness/timeouts) or an issue with the base map service we're using (Open Street Maps). 

One thing we could try is adjusting when the map is loaded in the application, but I'm not sure that would solve it. What do you think @BlakeDraper ?

**Comment by JChipault** [comment]
it's been reported by a partner in New York as well. So not just NWHC network.

**Comment by BlakeDraper** [comment]
@JChipault This is a tricky one in that there is very little we can do about this short of removing the basemap or perhaps just defaulting to a different one. The basemap comes from a 3rd party service, in this case as Lauren points out, Open Street Map. I do understand it is frustrating and ugly when those tiles don't load, but we cannot change how well that service loads on any given system. If its a real dealbreaker, I would suggest not displaying that particular basemap as the default and selecting one of the others instead.

**Comment by JChipault** [comment]
thank you both for looking into this and for the suggestions. are you able to tell which of the base maps would load the fastest? I like the "streets" view but it's pretty color-intensive so I'm wondering if you're able to tell if it's a smaller file to load than the current open street map. "Streets" seems to load faster on my computer but that doesn't feel like a very thorough test of the situation.

**Comment by BlakeDraper** [comment]
Hmm. No, we don't really have a good way to tell the fastest loader. These are all loaded as small image tiles and then stitched together by the map engine. Here's an example of one of the tiles that loads when you first open WHISPers: https://a.tile.openstreetmap.org/4/3/6.png. Because these are pre-generated, the colors are not so much a factor. What probably is a factor is the popularity of the basemap globally, as these servers are servicing thousands of requests per second. 

Also, every time you pan or zoom, new tiles have to be loaded to cover the map extent you are viewing. Occasionally there will be blips in this otherwise seamless process, which is what happens when you see those gray blocks missing. So we may just have to experiment; short of doing a deep dive into performance metrics per basemap, which does not seem worth our time at this juncture.

**Comment by JChipault** [comment]
Decision was made at today's meeting to try the "streets" layer and see if that performs better. Thanks!

**Comment by lprivette** [comment]
Forgot to mention this at the end of the call -- the streets layer performed much better on the same network where OSM tiles were taking 30s to load.

**Comment by JChipault** [comment]
fantastic. that's cause for hope!

**Comment by BlakeDraper** [comment]
Going to close this given the recent change of the default basemap.
