### ISSUE TITLE
"suspect" not floating up to event level appropriately

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#711]
We might have talked about this but I didn't see a github ticket yet....

Check out 200166 in the live version.

At the species level there's:
Blunt Trauma (NOS) suspect
Undetermined
Dehydration
Drowning (NOS) suspect
Emaciation (NOS)
Blunt Trauma (NOS)

In the event diagnosis dropdown options there's:
Blunt Trauma (NOS) suspect
Undetermined
Dehydration
Drowning (NOS) suspect
Emaciation (NOS)

.... but Blunt Trauma (NOS) at the species level should trump Blunt Trauma (NOS) suspect and only the not suspect version should be in the drop down at the event level.

Furthermore....
Blunt Trauma (NOS) suspect and Drowning (NOS) suspect are greyed out in the dropdown list because they've been selected by the epi but.....

neither of those options display on the event details page with the word suspect appended.

So dropdown should have 
Blunt Trauma (NOS)
Undetermined
Dehydration
Drowning (NOS) suspect
Emaciation (NOS)

with Blunt Trauma (NOS) and Drowning (NOS) suspect greyed out in the dropdown menu and displayed on the event details page.

**Comment by BlakeDraper** [comment]
@JChipault This event is now marked complete so I cannot mess with it to observe and test unless I set to incomplete. Since this is real data, I don't want to do that w/out your permission. Can we make this incomplete temporarily, or do you have another example where this is happening on a non-complete event? I suspect this will take a deep dive into logic and timing so I'd like an example to view.

**Comment by JChipault** [comment]
I re-created it in the test site (170782).

**Comment by JChipault** [comment]
I think Aaron did some tweaking to the display of suspect at the event level so that seems to be working different now on the test site than when I first reported this bug. It's displayed accurately on the event details page but still not quite right in the dropdown options. Here's a screen shot from the test site event wherein what's in the dropdown is different than what is displayed on the details page:

![image](https://user-images.githubusercontent.com/49287076/66430234-49fff200-e9df-11e9-9ca2-d081a60d6d0e.png)

**Comment by BlakeDraper** [comment]
@JChipault Here is how I currently do to create that list, so you can help me think through this:

1) On event details page load, loop through all the species diagnoses of all the location species of all the event locations and add each one to a list called  "Possible Event Diagnoses", unless it is already in that list (preventing duplicates). 
2) Add the Undetermined diagnosis to the list, unless that is there already. 
3) The dropdown itself has an embedded function that checks each option against the eventDiagnoses list and disables all the options that already exist as an event diagnosis (this is the graying out you see). 

These three steps happen also whenever a event refresh is triggered, which occurs after a species diagnosis is added (and really when anything is added or edited). I fully clear the list and build it again every time. 

Where I think the problem lies is this: both in step 1 and step 3, those checks for duplicates only check the diagnosis ID itself. So `Blunt Trauma (NOS)` and `Blunt Trauma (NOS) suspect` would be identical in this case since the diagnosis ID is the same. Only the `suspect` field differs (`false` and `true`, respectively). 

So it seems for those duplicate checks, we need to check the suspect field _in combination with_ the diagnosis field. This would mean both the suspect and non-suspect versions of a diagnosis would appear in the event diagnosis options list (if those both exist among the species diagnoses) - does that sound correct to you?

**Comment by JChipault** [comment]
If both botulism suspect and botulism (no suspect added on) are in the species list than ONLY the non-suspect option should show at the event level dropdown. If it's confirmed anywhere at the species level, we'll call it confirmed at the event level. So in this case, we'd only want "Blunt Trauma (NOS)" in the dropdown and not "Blunt Trauma (NOS) suspect"

**Comment by BlakeDraper** [comment]
Ok, fixed in code to only show non-suspect version of the diagnosis in the possible event diagnoses when both a suspect and non-suspect instance exist among the species diagnoses.

**Comment by JChipault** [comment]
@BlakeDraper I was cleaning up event 200166 by removing the old "drowning (NOS)" from the event diagnosis and adding "drowning (NOS) suspect" now that this bug was fixed. That went fine. I deleted the old errant event diagnosis and added the new correct one (with suspect appended). Then I went mark the event as "Complete" and got: Error. Event not updated. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data.

Buuuuuuut it did in fact update the event to complete and then let me fill in the quality check date no problem. 

So maybe absolutely fine now and just a one-off thing as I correct an old event to conform with the more recently instated business rules, but just wanted a record of the error message in case it meant something to you.
