### ISSUE TITLE
Show Service Request comments and responses on the the comments table tab

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#727]
Per email from Neil:

> service request comments don't seem to be being logged in the Comment Timeline.
> 
> also, there is a need to show the service request RESPONSE in the comment pane. This is obviously not a comment, but is important to see. One potential solution is to auto create a comment upon response? E.g. NWHC selects ‘Maybe’ from the response drop down and it creates an associated comment that reads “Response: Maybe”. We’re open to suggestions here.
_____________________________

@BlakeDraper The service request are not included in the `combined_comments` section of the eventdetails response. They are listed under `service_requests`. 

How about we make a separate table for them underneath the comments table? Maybe I'm overthinking it, but the service requests comments are a whole different type of comment than the  ones in the Comments table. OR should we see if they can be included in the `combined_comments` section?

**Comment by BlakeDraper** [comment]
@lprivette they should be in the combined comments. That list is generated server-side so I will create an issue for Aaron to add that. The only problem is, they do not have their own comment type - they are using "Other", which means it will not be very obvious what they are. As for the other issue - showing the response, that is a more complicated problem and needs a more custom solution. Will revisit that after some thought today. 

@nbaertlein the issue with displaying the service request comments in the main comment timeline table if they do not have their own type. They use the type "Other". Do you want to add a service request specific comment type so that it would be more evident what they are in the timeline?

**Comment by BlakeDraper** [comment]
@nbaertlein I am hesitant to auto-create a comment because it will be redundant outside the context of the comments timeline table. in all the other places it appears, it will have a request response plus a comment saying the same thing. I understand the desire to have those in the comment timeline, but our schema does not support that. It feels like a bad patch to create a comment for response, and we may also want a type for that (See above). Do we need to fully re-think how service requests are tracked now that the comment timeline exists?

**Comment by nbaertlein** [comment]
@BlakeDraper It should not matter what the comment category is as all comments, including service request comments, are in the same table (whispers_comment).  With every comment, the model (i.e., event, event group, event location, & service request) is captured (see content_type_id) and would provide context for comments, including service request comments.  I think we address this issue by requesting comment source instead of location (issue #724, number 2 ).  From an architecture standpoint, I don't think any changes are needed.  ...or am I missing something?

I understand the redundancy of a response comment, however we felt this would be the easiest solution to show responses to requests in the comment pane.  Best practices aside, is auto-creation of a service request comment developmentally problematic or costly?  Would you propose any other solutions?  I'm open to discuss further.

**Comment by BlakeDraper** [comment]
@nbaertlein sorry for the long gap here. You are correct that no architecture change is needed if we do exactly as you have requested and auto-generate a response comment when the response is updated. The place where this redundancy will be most evident is the service request section of the event details page. Your app, so we'll press forward with your request,

**Comment by BlakeDraper** [comment]
The action on this issue moved to here: https://github.com/USGS-WiM/whispersservices_django/issues/293

**Comment by lprivette** [comment]
Done in branch `727`.

Thanks to Aaron, service requests now show up in the comments table. I added a check to display "Service Request" in the source column for those comments.

I also verified that the auto-generated response comment is working and is in the comments table. On first glance it looks like it might be hard to determine which response goes with which service request.

**Comment by JChipault** [comment]
I'm not seeing "service request" as "comment source". Rest looks great!

![image](https://user-images.githubusercontent.com/49287076/68487628-09c3a780-0209-11ea-96fa-eb6652952363.png)

**Comment by JChipault** [comment]
@BlakeDraper not sure this is quite closed because we don't see "Service Request" in the comment source... or maybe you just fixed that?

**Comment by lprivette** [comment]
@JChipault Yep, we had forgotten to include a branch in the previous release. Blake has patched it now.

**Comment by JChipault** [comment]
sweet. thanks

**Comment by BlakeDraper** [comment]
Yep should be all good now with the live production version v2.8.2. This was my error.
