### ISSUE TITLE
WHISPers header logo image not rendering on reports

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#786]

**Comment by BlakeDraper** [comment]
@aaronstephenson before I contact EROS with this - do you have any ideas - possibly a config thing on our end, why this particular recently added image would be throwing a 403 forbidden on the test directory for WHISPers in EROS? 

https://whisperstest.wim.usgs.gov/assets/logo-transparent.png

I can confirm the file is there. Others at that same directory location do serve fine. Probably an EROS thing but checking w/you first.

**Comment by BlakeDraper** [comment]
Note that adjacent images also return a 403 on direct request (ex: https://whisperstest.wim.usgs.gov/assets/wim_abbr_black.png) but do load up in the app ok.

**Comment by aaronstephenson** [comment]
That's because the whispers client app is not at the root of the domain like it is for prod. We had to set up the test server this way to get the notifications version of the app to work. Everything you need for the test whispers app can be found in the whispers app folder:

https://whisperstest.wim.usgs.gov/whispers/assets/logo-transparent.png

**Comment by BlakeDraper** [comment]
Aha, so I have discovered the issue. Made no sense that all the other images were working (from same directory).

`logo-transparent.png` was being referenced in the code with an absolute path of `'/assets/logo-transparent.png'` vs the relative path from root like the others: `'./assets/w-logo.png'` with the little `.` being key.

**Comment by BlakeDraper** [comment]
Published with v2.11.1
