### ISSUE TITLE
dots on home page move into the ocean

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#835]
Got this screen shot from a partner in New York using chrome today:
![image](https://user-images.githubusercontent.com/49287076/73308164-476f1580-41e5-11ea-8e5d-1c7cf0f2fade.png)

I tried to recreate in firefox with WHISPers v2.12.1 and so ran the same search and then generated a search results report (since I suspected that's what the partner did because her homework this week was to test out the reports for us) and I got this on the home page after running the report:
![image](https://user-images.githubusercontent.com/49287076/73308261-7e452b80-41e5-11ea-8a75-3ff3fe9d42f4.png)

And on the report it looks like this (note dots in upper left corner of the map)
![image](https://user-images.githubusercontent.com/49287076/73308355-adf43380-41e5-11ea-9eef-85464db8613a.png)

The dots looked find for me on the home page BEFORE I ran the search summary report and when I hit refresh on my web browser, they looked good again:
![image](https://user-images.githubusercontent.com/49287076/73308478-ff042780-41e5-11ea-90a9-c5a304c844ad.png)

**Comment by BlakeDraper** [comment]
@lprivette I cannot recreate this on test. Can you give it a try?

**Comment by lprivette** [comment]
This happens for me after printing and then zooming the map.

**Steps to reproduce:**
1. Enter the search from the image (or any search with points on the map)
2. Generate a report and download report
3. Attempt to zoom on the Home map

This is very confusing because we don't use the home map to make our image on the pdf. I've ensured that there are no relics in the home component from when were were doing it there.

So my next best guess is that it's capturing the markers on both the home page component and the search component. In order to capture the markers to include them on the printout image, I select them with this on the search component `const myDivicons = $('.leaflet-marker-icon');` Both maps obviously will have that class, but I didn't know that it could grab the class that is a part of a separate component. Does that sound possible at Blake?

**Comment by BlakeDraper** [comment]
Not as part of a separate component, no. I'll dig into this a bit.

**Comment by BlakeDraper** [comment]
Fox done, and forthcoming in a release.

**Comment by BlakeDraper** [comment]
Published v2.12.2

**Comment by JChipault** [comment]
Just tried on 12.2.3 and lost my points altogether when I ran a search report and then hit the zoom in/zoom out buttons on the upper left of the map
![image](https://user-images.githubusercontent.com/49287076/74071479-99742000-49c9-11ea-8dcf-d5050a92af47.png)

**Comment by JChipault** [comment]
though just tried twice more and can't reproduce

**Comment by BlakeDraper** [comment]
I cannot reproduce either. Possible it was on another browser window that was still hitting the old version due to caching?
